services:
  SenseVoice:
    image: catcto/sensevoice
    container_name: SenseVoice
    restart: always
    ports:
      - "8080:8080"
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all